### ISSUE TITLE
Adding ISO code to base URL

### ISSUE THREAD

**Issue by compulshun** [therealmarius/Spotify-2-AppleMusic#11]
Hey there,

I can't get the script working and my guess is that it's because I'm in Canada. I'm not sure where exactly to edit the URL to add my country code or what exactly that would look like. from the looks of it, '&l=en-CA' needs to be added to the end of the request URL to add a track to a playlist but I'm a little intimidated at editing this line, not sure how to slide it in:

request = s.post(f"https://amp-api.music.apple.com/v1/me/library/playlists/{playlist_id}/tracks", json={"data":[{"id":f"{song_id}","type":"songs"}]})

**Comment by therealmarius** [comment]
Hi! Thanks for reaching out,

I understand your problem. Since you are in Canada all you need to do is to change the base URL (line 14 of `getitunesid.py`) to this:
```python
base_url = "https://itunes.apple.com/search?country=CA&media=music&entity=song&limit=5&term="
```
When you want to add your converted songs to your Apple Music, you don't need to change anything, since your cookies and your Apple ID are linked to a specific country, in your case Canada.

In fact, you need to change the storefront inside of the base url for a simple reason, it's because not all songs are available in all countries, and some songs does not have the same iTunes ID in different countries.

Let me know if it works for you
And enjoy your converted playlist!
Best,

**Comment by compulshun** [comment]
Ah, that's much simpler, thank you :). Everything's working great now.
