### ISSUE TITLE
can find barely any songs fix?

### ISSUE THREAD

**Issue by rednaow21** [therealmarius/Spotify-2-AppleMusic#31]
![image](https://github.com/therealmarius/Spotify-2-AppleMusic/assets/83751356/de056433-066b-4825-aae6-fff1340ce555)

**Comment by nf1973** [comment]
Hi @rednaow21 

I am pretty certain that the issue is the order of the columns in your exported file not matching the column order that this program is expecting.

Did you export the files from https://watsonbox.github.io/exportify/ or from https://exportify.net/ ?

I remember noticing a while back that the column order of the exported files are different between them.

(In your screenshot you see some ID number, Album Name and Date - you should see Track Title, Artist and Album.

I hope it helps you to get it working - I too can confirm that for my 10000 or so tracks it was around 99% successful.

Good luck!

**Comment by rednaow21** [comment]
Tried with the watsonbox variant and its working now. thanks a lot.

**Comment by dirtydurkin101** [comment]
I’m having the exact same issue but I did use the Watson box variant and it didn’t work.
