### ISSUE TITLE
Error 500 when running the script

### ISSUE THREAD

**Issue by Exilefalcon** [therealmarius/Spotify-2-AppleMusic#35]
I get the following exception when I run the script:
Exception: Error 500 while creating playlist liked!

I have created .dat files with the corresponding credentials just in case. Any reason why this might be happening?

PS: My country code is TR, if there are any restrictions I'm unaware of.

**Comment by therealmarius** [comment]
Hey,

Can you make sure you copied your connection data right ? Because it is CASE SENSITIVE. (It must include the word `Bearer` in the token part)

The error code 500 means that the Apple Music encountered an unexpected condition that prevented it from fulfilling the create playlist request. Basically, it's a generic error code to say that they don't know where it screwed up.

Regarding your country code, have you tried using Apple Music Web interface ? Just to see if there is any restrictions applying.

Best,
therealmarius

**Comment by Exilefalcon** [comment]
Hi, 

token.dat has Bearer, space and then the token. It seems correct.

![image](https://github.com/therealmarius/Spotify-2-AppleMusic/assets/32794929/7540958d-09a6-4cf9-9159-81bd4aabac1e)

**Comment by Exilefalcon** [comment]
Whoops, you were right. I missed a couple characters at the end of the Bearer token. Thank you so much for the quick help.
